### ISSUE TITLE
Clear a line when filled

### ISSUE THREAD

**Issue by TomFearn** [TomFearn/Classic-Tetris#3]
**User Story**
As a user I want to be able progress in the game and clear lines

**Acceptance Criteria**

- [ ] The game row is cleared when the row is full
- [ ] The rest of the blocks move down 

**Tasks**
- [ ] Loop through each row of the board and check it is filled
- [ ] Update the game board to remove a full row
- [ ] Update the game board to move the rest of the blocks down
